### PR TITLE
Add content checks before DOM loading and base CSS styling

### PR DESCRIPTION
**Pull request by chrmil11**
@natalieherrmann I added a check on DOM load to figure out which page we're on. We can change this so that everything is in the same function.

Also provided some base styling (at least for my page, but some of them carry over).

### CODE REVIEW

**Comment by natalieherrmann** [comment]
Looks good!

**Review by rafagan1 — COMMENTED** [review]
Looks good

**Review by rafagan1 — COMMENTED** [review]
Looks good

**Comment by chrmil11** [comment]
@aaldossari The ticket's page I think is @rafagan1's. He can take care of that change (although I think for clarity it would be good to have the age specification of child/adult/senior. (adult probably 18-65)

**Comment by chrmil11** [comment]
Just added some warning highlighting and styling for the form. Can someone check it and pull the change?

We also need to go back and clean up the javascript because the linter does throw warnings at us (plus we should probably stick to one DOM function).

(I also fixed the README)

**Review by aaldossari — APPROVED** [review]
Looks good

**Review by aaldossari — APPROVED** [review]

**Pull request merged**
