### PR TITLE
Add listener to check form input and enable/disable submit button

### PR DESCRIPTION
**Pull request by chrmil11**

### CODE REVIEW

**Review by rafagan1 — COMMENTED** [review]
Since the site.js file is shared by all pages, do you need to check if "submit_payment" and "payment_form" are null before using on lines 93 and 97.

**Comment by natalieherrmann** [comment]
What you did looks good, though I don't think we should have separate DOMContentLoaded event listeners. 

Maybe this should be a separate branch after, but we should add ids to each html page and put page-specific JS things in an if statement, so there'll be no null errors like Richard mentioned.

**Comment by aaldossari** [comment]
Good commits Christopher, but do we need console log output for the invalid data?

**Comment by chrmil11** [comment]
@natalieherrmann @rafagan1 good suggestion. I think using a unique id for each page's body tag would be a good identifier.

@aaldossari For now I'm just using it to make sure the functionality works. I'll replace them with warnings to show up on the page.

**Pull request merged**
