### PR TITLE
Change name of id and set path to css/js files

### PR DESCRIPTION
**Pull request by rafagan1**
Did more than the commit statement indicates. Added styling JS for the time and tickets page.  Will need to organize both files later and clean up lint errors on JS file. Looking for feedback especially on the functionality of the JS logic.  Anything I should add/delete?

### CODE REVIEW

**Comment by natalieherrmann** [comment]
In the future, you should definitely make smaller commits of everything you're doing. 

So here, dateSelected is null because you're referencing it with id 'pick-date' when it's 'date'. The event listeners for submit_showTime and ticketType aren't working for me, I think it's necessary to do`e.preventDefault()` in the function for the event so that clicking the submit button doesn't change the page before it does the things in the function. 

For example, this worked for me:
```
submit_showTime.addEventListener('click', function(e) {
            e.preventDefault();
            // Remove previous stored time and date
            localStorage.removeItem('time_movieTime');
            localStorage.removeItem('time_movieDate');

            // Get the selected time and date
            var dateSel = dateSelected.options[dateSelected.selectedIndex].text;
            var timeSel = timeSelected.options[timeSelected.selectedIndex].text;

            // Store the selected date and time
            localStorage.setItem('time_movieDate', dateSel);
            localStorage.setItem('time_movieTime', timeSel);

           // Go to next page
            document.location.assign('../tickets/');
        });
```
This also probably works better than the function storeDateAndTime() since it's trying to access dateSelected and timeSelected, which wouldn't be defined in the context of the function.

Also, it would be good to add an id to your html or body tag so the JS can check which page it's on before doing page-specific JS.

**Comment by rafagan1** [comment]
Subsequent pull request on the same feature branch

**Comment by chrmil11** [comment]
Looks better. Also is there a reason you're setting a 10-ticket max for the inputs? Just curious.

**Comment by rafagan1** [comment]
Thanks for reviewing, Christopher. No real reason for the 10-ticket max. I
believe one of the sites I previewed had a ticket max, 60 I believe. There
was an associating message specifying the ticket max. I never got around to
implementing it. I'll look into doing that or get rid of the max value.

**Review by aaldossari — COMMENTED** [review]
looks good

**Comment by natalieherrmann** [comment]
Looks good. Though maybe the minimum value for the tickets should be changed too, since once you increment it you're not allowed to go back to 0? Also, it looks like a line got into your CSS file from merging

**Pull request merged**
