### PR TITLE
Draft pull request for some changes in seating index

### PR DESCRIPTION
**Pull request by aaldossari**
Added text area to show the seats number and correct some tags

### CODE REVIEW

**Comment by chrmil11** [comment]
Merge conflict with `README.md`. Just remove the additional text and that should be okay.

You're also removing files from 'SeatMap'. Is this correct? (I'm assuming it's all being moved over to 'seating' instead)

**Review by rafagan1 — COMMENTED** [review]
Looks good. Same question as Christopher about moving file.

**Comment by natalieherrmann** [comment]
Ditto what they said. Also "Screan" should be "Screen" inside of the header and it looks like you have an extra </li> after the </ol> at the very end.

**Comment by natalieherrmann** [comment]
Oops in my previous comment it looks like some stuff got cut out: it looks like there's an extra `</li>` after the `</ol>` at the very end

**Comment by aaldossari** [comment]
@chrmil11 yes correct "SeatMap" is the wrong file.

@natalieherrmann thanks corrected the spelling to screen. and the `</li>` to close textarea.

**Comment by natalieherrmann** [comment]
Ok, though the li for textarea will need to be inside an ul/ol

**Review by rafagan1 — COMMENTED** [review]
ok

**Review by rafagan1 — COMMENTED** [review]
ok

**Pull request merged**
